version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats-streaming:0.22.0
    environment:
      - NATS_STREAMING_CLUSTER_ID=test-cluster
    ports:
      - "4222:4222"    # nats
      - "8222:8222"    # monitoring (optional)
    command: ["-m", "8222"] # enable monitoring

volumes:
  pgdata:
